
# This file is used to configure your Supabase project.
# It's very minimal at the moment and uses default values.
# Full reference is here: https://github.com/supabase/cli/blob/main/pkg/cmd/root/config/config.go

project_id = "kbnaromrpwermjasjevd"
[functions.create-checkout]
verify_jwt = true
[functions.verify-session]
verify_jwt = true
[functions.generar-reporte-chatgpt]
verify_jwt = true
[functions.generar-reporte-chatgpt-v2]
verify_jwt = true
