// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kbnaromrpwermjasjevd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtibmFyb21ycHdlcm1qYXNqZXZkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcwNjYyMjMsImV4cCI6MjA2MjY0MjIyM30.czFeh3Ra9mlDzH6JO8Swfk5x3nWdIHqY44PjC5uUyDM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);